language: go
go:
  - "1.10.x"
  - "1.11.x"
  - "1.12.5"
  - "1.12.x"
  - "1.x"
  - "master"

notifications:
  irc:
    channels:
      - "chat.freenode.net#namecoin-dev"
    on_success: never

addons:
  apt:
    packages:
      - libcap-dev
      - gcc-multilib
      - libc6-dev:i386
      - libcap-dev:i386

sudo: false

install:
  - if [[ "${NO_NAMECOIN_TLS}" = 1 ]]; then TAGS="no_namecoin_tls"; fi
  - if [[ "${NO_NAMECOIN_TLS}" = 0 ]]; then TAGS=""; fi
  - go get -tags "$TAGS" -d -v -t ./...
  - GOXSYS_BRANCH=master
  # goxsys bug for Go 1.11 and earlier: https://github.com/golang/go/issues/34742
  - if [[ "$(go version)" =~ go1.[56789] ]]; then GOXSYS_BRANCH=release-branch.go1.13; fi
  - if [[ "$(go version)" =~ go1.1[01] ]]; then GOXSYS_BRANCH=release-branch.go1.13; fi
  - pushd $(go env GOPATH)/src/golang.org/x/sys; git checkout $GOXSYS_BRANCH; popd
  - GOXNET_BRANCH=master
  # goxnet dropped support for old go stdlib
  - if [[ "$(go version)" =~ go1.[56789] ]]; then GOXNET_BRANCH=release-branch.go1.12; fi
  - if [[ "$(go version)" =~ go1.1[01] ]]; then GOXNET_BRANCH=release-branch.go1.12; fi
  - pushd $(go env GOPATH)/src/golang.org/x/net; git checkout $GOXNET_BRANCH; popd
  - go get -tags "$TAGS" -v -t ./...
  - env GOOS=windows GOARCH=amd64 go get -tags "$TAGS" -d -v -t ./...
script:
  - source ./.travis/script
after_success:
  - source ./.travis/after_success

env:
  global:
    # GITHUB_TOKEN for automatic releases
    - secure: "at1oJs7ib7glx3W+zk+OkT041LdknVXirIhN403CIihVUrlOhODY7yCTgvF4Rk0jYBJiT35Q2qxpgfWF2qGnsNsQmjG3ydDWQDCepDc/CgXfLyoiSTJK5vTK72dYWTVsBTycXbj1CbSy2X2ah/KWjc4RcgZ67ER7mDpRU5nFeow="
    # Set this to the Go version to use for releases (must appear in version list above).
    - RELEASE_GO_VERSION="1.12.5"
  matrix:
    - NO_NAMECOIN_TLS=1
    - NO_NAMECOIN_TLS=0
